Araretama.BomNaEscolaBomDeBola.Site/Controllers/AulaController.cs
using Araretama.BomNaEscolaBomDeBola.DataAccess.Entity.Context;
using Araretama.BomNaEscolaBomDeBola.Domain;
using Araretama.BomNaEscolaBomDeBola.Repository.Entity;
using AraretamaRepositoy;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Araretama.BomNaEscolaBomDeBola.Site.Controllers
{
    public class AulaController : Controller
    {
        private DbContext _Context;
        PresencaRepository PresencaRepository;
        AulaRepository AulaRepository;
        TurmaRepository TurmaRepository;

        private IAraretamaCommonRepository<Aula, int> _repository = new AulaRepository(new BomNaEscolaBomDeBolaDbContext());
        

        public AulaController()
        {
            PresencaRepository = new PresencaRepository(new BomNaEscolaBomDeBolaDbContext());
            AulaRepository = new AulaRepository(new BomNaEscolaBomDeBolaDbContext());
            TurmaRepository = new TurmaRepository(new BomNaEscolaBomDeBolaDbContext());
        }

       

        public ActionResult Index()
        {
            List<Aula> a = _repository.All().OrderBy(x => x.DataAula).ToList(); 
            
            return View(a);
        }

        public ActionResult Details(int id)
        {
            return View(AulaRepository.DetalhesAula(id));
        }


        public ActionResult Create()
        {
            List<Turma> Turmas = TurmaRepository.All();
            ViewBag.turmas = Turmas;
            return View();
        }


        [HttpPost]
        public ActionResult Create(Aulas aulas, FormCollection collection)
        {
            List<Turma> Turmas = TurmaRepository.All();
            ViewBag.turmas = Turmas;
            if (ModelState.IsValid)
            {
                try
                {
                    Turma turma = TurmaRepository.ByKey(aulas.IDTurma);
                    int dia = this.DiaDaSemana(turma.DiaSemana);
                    while (aulas.DataInicial <= aulas.DataFinal)
                    {
                        if ((int)aulas.DataInicial.DayOfWeek == dia)
                        {
                            Aula aula = new Aula();
                            aula.DataAula = aulas.DataInicial;
                            aula.TurmaID = aulas.IDTurma;
                            aula.DataEnvio = DateTime.Now;
                            _repository.Insert(aula);
                        }
                        aulas.DataInicial = aulas.DataInicial.AddDays(1);
                    }
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    return View();
                }
            }
            return View();
        }

        private int DiaDaSemana(string dia)
        {
            if (dia.Equals("Domingo")){
                return 0;
            }
            else 
            if (dia.Equals("Segunda-Feira"))
            {
                return 1;
            }
            else 
            if(dia.Equals("Terça-Feira"))
            {
                return 2;
            }
            else 
            if (dia.Equals("Quarta-Feira"))
            {
                return 3;
            }
            else
            if (dia.Equals("Quinta-Feira"))
            {
                return 4;
            }
            else
            if (dia.Equals("Sexta-Feira"))
            {
                return 5;
            }
            else
            if (dia.Equals("Sábado"))
            {
                return 6;
            }
                  
            return 0;
        }
        /*

        public ActionResult Chamada(int id)
        {
            return View(AulaRepository.DetalhesAula(id));
        }

        [HttpPost]
        public ActionResult Chamada(int id, Aula aula, FormCollection collection)
        {
            try
            {
                aula.DataAula = Convert.ToDateTime(collection["DataAula"]);
                aula.Id = id;
                aula.TurmaID = aula.Turma.Id;
                aula.DataEnvio = DateTime.Now;
                List<Presenca> presencas = aula.Presencas.FindAll(p => p.Presente);
                foreach (Presenca i in presencas)
                {
                    try
                    {
                        PresencaRepository.Update(i);
                    }
                    catch
                    {
                        PresencaRepository.Insert(i);
                    }

                }
                _repository.Update(aula);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(AulaRepository.DetalhesAula(id));
            }
        }

    */
        public ActionResult Edit(int id)
        {
            return View(AulaRepository.DetalhesAula(id));
        }
        

        [HttpPost]
        public ActionResult Edit(int id, Aula aula,FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Aula au = _repository.ByKey(id);
                    au.DataEnvio = DateTime.Now;
                    List<Presenca> presencas = aula.Presencas.FindAll(p => p.Presente);
                    foreach (Presenca i in presencas)
                    {
                        try
                        {
                            PresencaRepository.Update(i);
                        }
                        catch
                        {
                            PresencaRepository.Insert(i);
                        }
                    }
                    _repository.Update(au);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return View(AulaRepository.DetalhesAula(id));
                }
            }
            return View(AulaRepository.DetalhesAula(id));
        }

        public ActionResult Delete(int id)
        {
            return View(_repository.ByKey(id));
        }

        [HttpPost]
        public ActionResult Delete(int id, Aula aula, FormCollection collection)
        {
            try
            {
                _repository.DeleteByKey(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(_repository.ByKey(id));
            }
        }
    }
}

Araretama.BomNaEscolaBomDeBola.Site/Views/Aula/Create.cshtml
@model Araretama.BomNaEscolaBomDeBola.Domain.Aulas

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<h2>Criação de periodo de aula</h2>
@using (Html.BeginForm("Create", "Aula", FormMethod.Post, new { @id = "demo-form2", @class = "form-horizontal form-label-left" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h5>Digite um periodo de aula a ser criado</h5>
        <hr />



        <div class="form-group">
            @Html.LabelFor(model => model.DataInicial, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
            <d <div class="col-md-6 col-sm-6 col-xs-12">
                @Html.EditorFor(model => model.DataInicial, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                @Html.ValidationMessageFor(model => model.DataInicial, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.DataFinal, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
            <div class="col-md-6 col-sm-6 col-xs-12">
                @Html.EditorFor(model => model.DataFinal, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                @Html.ValidationMessageFor(model => model.DataFinal, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.IDTurma, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
            <div class="col-md-6 col-sm-6 col-xs-12">
                @Html.DropDownListFor(model => model.IDTurma, new SelectList(ViewBag.turmas, "Id", "Nome"), new { @class = "form-control col-md-7 col-xs-12" })
                @Html.ValidationMessageFor(model => model.IDTurma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-sm-offset-2 col-md-7 col-sm-7 col-xs-12">
                <button type="submit" class="btn btn-group-justified btn-round btn-success">
                    <i class="fa fa-save"></i> <span>Salvar</span>
                </button>
            </div>
        </div>
    </div>
}

Araretama.BomNaEscolaBomDeBola.Site/Views/Aula/Delete.cshtml
@model Araretama.BomNaEscolaBomDeBola.Domain.Aula

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Aula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DataAula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataAula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataEnvio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataEnvio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IDTurma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDTurma)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlunosPresentes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlunosPresentes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Araretama.BomNaEscolaBomDeBola.Site/Views/Aula/Details.cshtml
@model Araretama.BomNaEscolaBomDeBola.Domain.Aula

@{
    /**/

    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<h2><strong>Aula -  @Html.DisplayFor(model => model.DataAula) </strong></h2>

<div>

    <div class="col-md-8">
        <p>
            <strong> @Html.DisplayNameFor(model => model.DataEnvio) </strong>:  @Html.DisplayFor(model => model.DataEnvio)
        </p>

        <p>
            <strong> @Html.DisplayNameFor(model => model.TurmaID)</strong>: @Html.DisplayFor(model => model.Turma.Nome)
        </p>
        <p>
            <strong> @Html.DisplayNameFor(model => model.AlunosPresentes)</strong>: @Html.DisplayFor(model => model.AlunosPresentes)
        </p>

    </div>
    <div class="col-md-4">
       @if (DateTime.Today == Model.DataAula) 
        {
            <a href="@Url.Action("Chamada", "Aula", new { id = Model.Id } )" class="btn btn-round btn-primary">
                <i class="fa fa-calendar-check-o "></i>
                <span>
                    Chamada
                </span>
            </a>
        }
        else
        {
            <a href="@Url.Action("Edit", "Aula", new { id = Model.Id } )" class="btn btn-round btn-primary">
                <i class="fa fa-edit"></i>
                <span>
                    Editar
                </span>
            </a>
        }

        <a href="@Url.Action("Index", "Aula"  )" class="btn btn-round btn-default">
            <i class="fa fa-undo"></i>
            <span>
                Voltar
            </span>
        </a>

    </div>
</div>
    @if (Model.Presencas != null)
    {
        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap jambo_table bulk_action" cellspacing="0" width="100%">
            <thead class="">
                <tr>
                    <th class="">@Html.DisplayNameFor(model => model.Presencas[0].Aluno.Id)</th>
                    <th> @Html.DisplayNameFor(model => model.Presencas[0].Presente)</th>
                    <th>@Html.DisplayNameFor(model => model.Presencas[0].Aluno.Nome)</th>

                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Presencas.Count; i++)
                {
                <tr>
                    <td>@Html.DisplayFor(model => model.Presencas[i].Aluno.Id)</td>
                    
                    <td>
                        
                        @Html.EditorFor(model => model.Presencas[i].Presente, new { htmlAttributes = new { @class = "icheckbox_flat-blue", @disabled = "disabled" } })
                    </td>
                    <td>@Html.DisplayFor(model => model.Presencas[i].Aluno.Nome)</td>

                </tr>
                }
            </tbody>

        </table>
    }
    <br />
    

Araretama.BomNaEscolaBomDeBola.Site/Views/Aula/Edit.cshtml
@model Araretama.BomNaEscolaBomDeBola.Domain.Aula

@{
    /**/

    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div>

    <h2><strong>Aula -  @Html.DisplayFor(model => model.DataAula) </strong></h2>
    @Html.HiddenFor(model => model.Turma.Id)
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.DataAula)

    <div class="col-md-8">
        <p>
            <strong> @Html.DisplayNameFor(model => model.DataEnvio) </strong>:  @Html.DisplayFor(model => model.DataEnvio)
        </p>

        <p>
            <strong> @Html.DisplayNameFor(model => model.Turma)</strong>: @Html.DisplayFor(model => model.Turma.Nome)
        </p>
        <p>
            <strong> @Html.DisplayNameFor(model => model.AlunosPresentes)</strong>: @Html.DisplayFor(model => model.AlunosPresentes)
        </p>

    </div>
    <div class="col-md-4">

        <button class="btn btn btn-round btn-success" type="submit" value="Salvar"> <i class="glyphicon glyphicon-floppy-save"></i> Salvar</button>


        <a href="@Url.Action("Details", "Aula", new { id = Model.Id })" class="btn btn-round btn-default">
            <i class="fa fa-undo"></i>
            <span>
                Voltar
            </span>
        </a>

    </div>
</div>
    if (Model.Presencas != null)
    {
        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap jambo_table bulk_action" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Presencas[0].Aluno.Id)</th>
                    <th> @Html.DisplayNameFor(model => model.Presencas[0].Presente)</th>
                    <th>@Html.DisplayNameFor(model => model.Presencas[0].Aluno.Nome)</th>

                </tr>
            </thead>
            <tbody>

                @for (int i = 0; i < Model.Presencas.Count; i++)
                {
                    @Html.HiddenFor(model => model.Presencas[i].IDAluno)
                    @Html.HiddenFor(model => model.Presencas[i].IDAula)
                    @Html.HiddenFor(model => model.Presencas[i].id)
                    <tr>
                        <td>@Html.DisplayFor(model => model.Presencas[i].Aluno.Id)</td>

                        <td>
                            @Html.EditorFor(model => model.Presencas[i].Presente, new { htmlAttributes = new { @class = "icheckbox_flat-blue" } })
                            

                        </td>
                        <td>@Html.DisplayFor(model => model.Presencas[i].Aluno.Nome)</td>

                    </tr>
                }
            </tbody>

        </table>
    }

}

Araretama.BomNaEscolaBomDeBola.Site/Views/Aula/Index.cshtml
@model IEnumerable<Araretama.BomNaEscolaBomDeBola.Domain.Aula>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<h2>Aulas</h2>


<div class="table-responsive">
    <table class="table table-striped jambo_table bulk_action">
        <thead>
            <tr class="headings">
                <th>
                    @Html.DisplayNameFor(model => model.DataAula)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DataEnvio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Turma.Nome)
                </th>
                <th class="column-title">Ver </th>
                <th class="column-title">Editar</th>
                <th class="column-title">Excluir</th>

            </tr>
        <thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DataAula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataEnvio)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Turma.Nome)
                </td>

                <td class=" "> <a class="btn btn-primary" href="@Url.Action("Details", "Aula" , new { id = item.Id })"><i class="fa fa-plus"></i></a> </td>
                @if (DateTime.Today == item.DataAula)
                {
                    <td class=" "> <a class="btn btn-warning" href="@Url.Action("Edit", "Aula" , new { id = item.Id })"><i class="fa fa-calendar-check-o"></i></a> </td>
                }
                else
                {
                    <td class=" "> <a class="btn btn-warning" href="@Url.Action("Edit", "Aula" , new { id = item.Id })"><i class="fa fa-pencil"></i></a> </td>
                }
                
                <td class=" "> <a class="btn btn-danger" href="@Url.Action("Delete", "Aula" , new { id = item.Id })"><i class="fa fa-trash"></i></a> </td>

            </tr>
            }
        </tbody>
    </table>

    </div>