Araretama.BomNaEscolaBomDeBola.Site/Controllers/VoluntarioController.cs
using Araretama.BomNaEscolaBomDeBola.DataAccess.Entity.Context;
using Araretama.BomNaEscolaBomDeBola.Domain;
using Araretama.BomNaEscolaBomDeBola.Repository.Entity;
using AraretamaRepositoy;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Araretama.BomNaEscolaBomDeBola.Site.Controllers
{
   // [Authorize(Roles = "Administrador")]
    public class VoluntarioController : Controller
    {
        private DbContext _Context;
        TurmaRepository TurmaRepository;

        private IAraretamaCommonRepository<Voluntario, int> _repository = new VoluntarioRepository(new BomNaEscolaBomDeBolaDbContext());

        public VoluntarioController()
        {
            TurmaRepository = new TurmaRepository(new BomNaEscolaBomDeBolaDbContext());
        }

        public ActionResult Index()
        {
            return View(_repository.All());
        }

        public ActionResult Details(int id)
        {
            Voluntario voluntario = _repository.ByKey(id);
            voluntario.Turma.Add(TurmaRepository.All().Where(p => p.Id == voluntario.IDTurma).FirstOrDefault());
            return View(voluntario);
        }


        public ActionResult Create()
        {
            List<Turma> Turmas = TurmaRepository.All();
            ViewBag.turmas = Turmas;

            return View();
        }

        [HttpPost]
        public ActionResult Create(Voluntario voluntario, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _repository.Insert(voluntario);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    List<Turma> Turmas = TurmaRepository.All();
                    ViewBag.turmas = Turmas;

                    return View(voluntario);
                }
            }
            return View(voluntario);
        }
        
        public ActionResult Edit(int id)
        {
            List<Turma> Turmas = TurmaRepository.All();
            ViewBag.turmas = Turmas;
            Voluntario voluntario = _repository.ByKey(id);
            voluntario.Turma.Add(Turmas.Where(p => p.Id == voluntario.IDTurma).FirstOrDefault());
            return View(voluntario);
        }

        [HttpPost]
        public ActionResult Edit(int id, Voluntario voluntario, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _repository.Update(voluntario);
                    return RedirectToAction("Index");
                }
                catch
                {
                    List<Turma> Turmas = TurmaRepository.All();
                    ViewBag.turmas = Turmas;
                    return View(voluntario);
                }
            }
            return View(voluntario);
        }
        
        public ActionResult Delete(int id)
        {
            Voluntario voluntario = _repository.ByKey(id);
            voluntario.Turma.Add(TurmaRepository.All().Where(p => p.Id == voluntario.IDTurma).FirstOrDefault());
            return View(voluntario);
        }
        
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                _repository.DeleteByKey(id);
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return View(_repository.ByKey(id));

            }
        }
    }
}

Araretama.BomNaEscolaBomDeBola.Site/Views/Voluntario/Create.cshtml
@model Araretama.BomNaEscolaBomDeBola.Domain.Voluntario
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

@using (Html.BeginForm("Create", "Voluntario", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <h4>Cadastro de Voluntário</h4>
        <hr />
    

    <div class="form-group">
        @Html.LabelFor(model => model.IDTurma, htmlAttributes: new { @class = "  control-label col-md-3 col-sm-3 col-xs-12" })
        <div class="col-md-6 col-sm-6 col-xs-12">
            @Html.DropDownListFor(model => model.IDTurma, new SelectList(ViewBag.turmas, "Id", "Nome"), new { @class = "form-control " })
            @Html.ValidationMessageFor(model => model.IDTurma, "", new { @class = "text-danger" })
        </div>

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
        <div class="col-md-6 col-sm-6 col-xs-12">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
        <div class="col-md-6 col-sm-6 col-xs-12">
            @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
        <div class="col-md-6 col-sm-6 col-xs-12">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contato, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
        <div class="col-md-6 col-sm-6 col-xs-12">
            @Html.EditorFor(model => model.Contato, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contato, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-sm-offset-2 col-md-7 col-sm-7 col-xs-12">
            <button type="submit" class="btn btn-group-justified btn-round btn-success">
                <i class="fa fa-save"></i> <span>Salvar</span>
            </button>
        </div>
    </div>

   
</div>
}

Araretama.BomNaEscolaBomDeBola.Site/Views/Voluntario/Delete.cshtml
@model Araretama.BomNaEscolaBomDeBola.Domain.Voluntario

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Voluntário</h2>
                <div class="alignright ">


                    @using (Html.BeginForm("Delete", "Voluntario", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-actions no-color">
                            <button type="submit" value="Delete" class="btn btn-round btn-danger">
                                <i class="fa fa-trash"></i> Excluir
                            </button>

                        </div>
                    }

                </div>

                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <section class="content invoice">
                    <!-- title row -->
                    <div class="row">
                        <div class="col-xs-12 invoice-header">
                            <h1>
                                <i class="fa fa-heart"></i>  @Html.DisplayFor(model => model.Nome)

                            </h1>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- info row -->
                    <div class="row invoice-info">
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.Contato)
                                </strong>

                                <br>@Html.DisplayFor(model => model.Contato)
                            </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.Email)
                                </strong>

                                <br>@Html.DisplayFor(model => model.Email)
                            </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.Senha)
                                </strong>

                                <br>@Html.DisplayFor(model => model.Senha)
                            </address>
                        </div>



                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                    @if (Model != null && Model.Turma != null)
                    {
                        if (Model.Turma.Count > 0)
                        {
                            <div class="row">
                                <div class="col-xs-12 table">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>Turma</th>
                                                <th>Alunos</th>
                                                <th>Horario Inicial</th>
                                                <th>Horário Final</th>
                                                <th>Dia</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @for (var i = 0; i < Model.Turma.Count; i++)
                                            {
                                                <tr>
                                                    <td>@Html.DisplayFor(model => model.Turma[i].Nome)</td>
                                                    <td>@Html.DisplayFor(model => model.Turma[i].QuantidadeDeAlunos)</td>
                                                    <td>@Html.DisplayFor(model => model.Turma[i].HorarioInicial)</td>
                                                    <td>@Html.DisplayFor(model => model.Turma[i].HorarioFinal)</td>
                                                    <td>@Html.DisplayFor(model => model.Turma[i].DiaSemana)
                                                    <td></td>
                                                </tr>
                                            }



                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        }
                    }
                </section>
            </div>
        </div>
    </div>
</div>

Araretama.BomNaEscolaBomDeBola.Site/Views/Voluntario/Details.cshtml
@model Araretama.BomNaEscolaBomDeBola.Domain.Voluntario

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}



<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Voluntário</h2>
                <div class="alignright ">
                    <a href="@Url.Action("Edit", "Voluntario", new { id = Model.Id } )" class="btn btn-round btn-primary">
                        <i class="fa fa-edit"></i>
                        Editar
                    </a>
                </div>

                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <section class="content invoice">
                    <!-- title row -->
                    <div class="row">
                        <div class="col-xs-12 invoice-header">
                            <h1>
                                <i class="fa fa-heart"></i>  @Html.DisplayFor(model => model.Nome)

                            </h1>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- info row -->
                    <div class="row invoice-info">
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.Contato)
                                </strong>

                                <br>@Html.DisplayFor(model => model.Contato)
                            </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.Email)
                                </strong>

                                <br>@Html.DisplayFor(model => model.Email)
                            </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.Senha)
                                </strong>

                                <br>@Html.DisplayFor(model => model.Senha)
                            </address>
                        </div>

                      

                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                    @if (Model != null && Model.Turma != null)
                    {
                        if (Model.Turma.Count > 0)
                        {
                            <div class="row">
                                <div class="col-xs-12 table">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>Turma</th>
                                                <th>Alunos</th>
                                                <th>Horario Inicial</th>
                                                <th>Horário Final</th>
                                                <th>Dia</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @for (var i = 0; i < Model.Turma.Count; i++)
                                            {
                                                <tr>
                                                    <td>@Html.DisplayFor(model => model.Turma[i].Nome)</td>
                                                    <td>@Html.DisplayFor(model => model.Turma[i].QuantidadeDeAlunos)</td>
                                                    <td>@Html.DisplayFor(model => model.Turma[i].HorarioInicial)</td>
                                                    <td>@Html.DisplayFor(model => model.Turma[i].HorarioFinal)</td>
                                                    <td>@Html.DisplayFor(model => model.Turma[i].DiaSemana)
                                                    <td></td>
                                                </tr>
                                            }



                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        }
                    }
                </section>
            </div>
        </div>
    </div>
</div>

Araretama.BomNaEscolaBomDeBola.Site/Views/Voluntario/Edit.cshtml
@model Araretama.BomNaEscolaBomDeBola.Domain.Voluntario

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <div class="form-horizontal">
        <h4>Editar Voluntário</h4>
        <hr />
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)



    <div class="form-group">
        @Html.LabelFor(model => model.IDTurma, htmlAttributes: new { @class = "  control-label col-md-3 col-sm-3 col-xs-12" })
        <div class="col-md-6 col-sm-6 col-xs-12">
            @Html.DropDownListFor(model => model.IDTurma, new SelectList(ViewBag.turmas, "Id", "Nome"), new { @class = "form-control " })
            @Html.ValidationMessageFor(model => model.IDTurma, "", new { @class = "text-danger" })
        </div>

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
        <div class="col-md-6 col-sm-6 col-xs-12">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
        <div class="col-md-6 col-sm-6 col-xs-12">
            @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
        <div class="col-md-6 col-sm-6 col-xs-12">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contato, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
        <div class="col-md-6 col-sm-6 col-xs-12">
            @Html.EditorFor(model => model.Contato, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contato, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-sm-offset-2 col-md-7 col-sm-7 col-xs-12">
            <button type="submit" class="btn btn-group-justified btn-round btn-success">
                <i class="fa fa-save"></i> <span>Salvar</span>
            </button>
        </div>
    </div>
</div>
}

Araretama.BomNaEscolaBomDeBola.Site/Views/Voluntario/Index.cshtml
@model IEnumerable<Araretama.BomNaEscolaBomDeBola.Domain.Voluntario>

@{
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}




<p>
    <h2>Voluntários</h2>
</p>
@if (Model != null)
{
    <div class="">
        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap jambo_table" cellspacing="0" width="100%">
            <!--<table id="datatable-buttons" class="table table-bordered table-striped jambo_table bulk_action">-->
            <thead>
                <tr class="headings">
                    <th class="column-title"> @Html.DisplayNameFor(model => model.Nome) </th>
                    <th class="column-title"> @Html.DisplayNameFor(model => model.Email) </th>
                    <th class="column-title">@Html.DisplayNameFor(model => model.Contato) </th>
                    <th class="column-title">Ver </th>
                    <th class="column-title">Editar</th>
                    <th class="column-title">Excluir</th>

                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="even pointer">
                        <td class=" ">@Html.DisplayFor(modelItem => item.Nome)</td>
                        <td class=" ">@Html.DisplayFor(modelItem => item.Email) </td>
                        <td class=" "> @Html.DisplayFor(modelItem => item.Contato)</td>
                        <td class=" text-center"> <a class="btn btn-primary" href="@Url.Action("Details", "Voluntario" , new { id = item.Id })"><i class="fa fa-plus"></i></a> </td>
                        <td class=" "> <a class="btn btn-warning" href="@Url.Action("Edit", "Voluntario" , new { id = item.Id })"><i class="fa fa-pencil"></i></a> </td>
                        <td class=" "> <a class="btn btn-danger" href="@Url.Action("Delete", "Voluntario" , new { id = item.Id })"><i class="fa fa-trash"></i></a> </td>
                    </tr>
                }


            </tbody>
        </table>

    </div>
}