Araretama.BomNaEscolaBomDeBola.Site/Controllers/TurmaController.cs
using Araretama.BomNaEscolaBomDeBola.DataAccess.Entity.Context;
using Araretama.BomNaEscolaBomDeBola.Domain;
using Araretama.BomNaEscolaBomDeBola.Repository.Entity;
using AraretamaRepositoy;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Araretama.BomNaEscolaBomDeBola.Site.Controllers
{
    public class TurmaController : Controller
    {
        private DbContext _Context;
        AlunoRepository AlunoRepository;
        VoluntarioRepository VoluntarioRepository;

        private IAraretamaCommonRepository<Turma, int> _repository = new TurmaRepository(new BomNaEscolaBomDeBolaDbContext());
        
        public TurmaController()
        {
            AlunoRepository = new AlunoRepository(new BomNaEscolaBomDeBolaDbContext());
            VoluntarioRepository = new VoluntarioRepository(new BomNaEscolaBomDeBolaDbContext());
        }

        // GET: Turma
        public ActionResult Index()
        {
           
            List<Turma> a = _repository.All();
            foreach (var i in a)
            {
                i.Alunos = AlunoRepository.AlunosTurma(i.Id);
                i.Voluntarios = VoluntarioRepository.VoluntarioTurma(i.Id);
                i.QuantidadeDeAlunos = i.Alunos.Count();
            }
            return View(a);
        }

        // GET: Presenca/Details/5
        public ActionResult Details(int id)
        {
            Turma turma = _repository.ByKey(id);
            turma.Alunos = AlunoRepository.AlunosTurma(id);
            turma.Voluntarios = VoluntarioRepository.VoluntarioTurma(id);
            turma.QuantidadeDeAlunos = turma.Alunos.Count();
            return View(turma);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Turma turma, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _repository.Insert(turma);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }
        
        public ActionResult Edit(int id)
        {
            return View(_repository.ByKey(id));
        }

        [HttpPost]
        public ActionResult Edit(int id,Turma turma, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    turma.Id = id;
                    _repository.Update(turma);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        public ActionResult Delete(int id)
        {
            Turma turma = _repository.ByKey(id);
            turma.Alunos = AlunoRepository.AlunosTurma(id);
            turma.Voluntarios = VoluntarioRepository.VoluntarioTurma(id);
            turma.QuantidadeDeAlunos = turma.Alunos.Count();
            return View(turma);
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                _repository.DeleteByKey(id);
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                Turma turma = _repository.ByKey(id);
                turma.Alunos = AlunoRepository.AlunosTurma(id);
                turma.Voluntarios = VoluntarioRepository.VoluntarioTurma(id);
                 turma.QuantidadeDeAlunos = turma.Alunos.Count();
                return View(turma);

            }
        }
    }
}

Araretama.BomNaEscolaBomDeBola.Site/Views/Turma/Create.cshtml
@model Araretama.BomNaEscolaBomDeBola.Domain.Turma

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<div class="form-horizontal">
    <h4>Nova Turma</h4>
    <hr />
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
            <div class="col-md-6 col-sm-6 col-xs-12">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdadeMinima, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
            <div class="col-md-6 col-sm-6 col-xs-12">
                @Html.EditorFor(model => model.IdadeMinima, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdadeMinima, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdadeMaxima, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
            <div class="col-md-6 col-sm-6 col-xs-12">
                @Html.EditorFor(model => model.IdadeMaxima, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdadeMaxima, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.HorarioInicial, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
            <div class="col-md-6 col-sm-6 col-xs-12">
                @Html.EditorFor(model => model.HorarioInicial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HorarioInicial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HorarioFinal, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
            <div class="col-md-6 col-sm-6 col-xs-12">
                @Html.EditorFor(model => model.HorarioFinal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HorarioFinal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            @Html.LabelFor(model => model.DiaSemana, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
            <div class="col-md-6 col-sm-6 col-xs-12">
                <select id="DiaSemana" name="DiaSemana" class="form-control">
                    <option value="Domingo">Domingo</option>
                    <option value="Segunda-Feira">Segunda-Feira</option>
                    <option value="Terça-Feira">Terça-Feira</option>
                    <option value="Quarta-Feira">Quarta-Feira</option>
                    <option value="Quinta-Feira">Quinta-Feira</option>
                    <option value="Sexta-Feira">Sexta-Feira</option>
                    <option value="Sábado">Sábado</option>
                </select>
                @Html.ValidationMessageFor(model => model.DiaSemana, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-sm-offset-2 col-md-7 col-sm-7 col-xs-12">
                <button type="submit" class="btn btn-group-justified btn-round btn-success">
                    <i class="fa fa-save"></i> <span>Salvar</span>
                </button>
            </div>
        </div>
    </div>
}

Araretama.BomNaEscolaBomDeBola.Site/Views/Turma/Delete.cshtml
@model Araretama.BomNaEscolaBomDeBola.Domain.Turma

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Turma</h2>
                <div class="alignright ">

                    @using (Html.BeginForm("Delete", "Turma", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-actions no-color">
                            <button type="submit" value="Delete" class="btn btn-round btn-danger">
                                <i class="fa fa-trash"></i> Excluir
                            </button>

                        </div>
                    }
                </div>


                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <section class="content invoice">
                    <!-- title row -->
                    <div class="row">
                        <div class="col-xs-12 invoice-header">
                            <h1>
                                <i class="fa  fa-users"></i>  @Html.DisplayFor(model => model.Nome)

                            </h1>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- info row -->
                    <div class="row invoice-info">
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.DiaSemana)
                                </strong>

                                <br>@Html.DisplayFor(model => model.DiaSemana)
                            </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.HorarioFinal)
                                </strong>

                                <br>@Html.DisplayFor(model => model.HorarioInicial)
                            </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.HorarioFinal)
                                </strong>

                                <br>@Html.DisplayFor(model => model.HorarioFinal)
                            </address>
                        </div>
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.IdadeMaxima)
                                </strong>

                                <br>@Html.DisplayFor(model => model.IdadeMaxima)
                            </address>
                        </div>
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.IdadeMinima)
                                </strong>

                                <br>@Html.DisplayFor(model => model.IdadeMinima)
                            </address>
                        </div>
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.QuantidadeDeAlunos)
                                </strong>

                                <br>@Html.DisplayFor(model => model.QuantidadeDeAlunos)
                            </address>
                        </div>



                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                    <hr />
                    <h2>
                        <i class="fa  fa-user"></i>  Alunos

                    </h2>
                    @if (Model != null && Model.Alunos != null)
                    {
                        if (Model.Alunos.Count > 0)
                        {
                            <div class="row">
                                <div class="col-xs-12 table">
                                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap jambo_table" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Nome</th>
                                                <th>Nascimento</th>
                                                <th>Escolaridade</th>
                                                <th>Contato</th>
                                                <th>Observação</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @for (var i = 0; i < Model.Alunos.Count; i++)
                                            {
                                                <tr>
                                                    <td>@Html.DisplayFor(model => model.Alunos[i].Id)</td>
                                                    <td>@Html.DisplayFor(model => model.Alunos[i].Nome)</td>
                                                    <td>@Html.DisplayFor(model => model.Alunos[i].DataNasc)</td>
                                                    <td>@Html.DisplayFor(model => model.Alunos[i].Serie)</td>
                                                    <td>@Html.DisplayFor(model => model.Alunos[i].Contato)</td>
                                                    <td>@Html.DisplayFor(model => model.Alunos[i].Observacao)</td>
                                                </tr>
                                            }



                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        }
                    }
                    <hr />
                    <h2>
                        <i class="fa  fa-heartbeat"></i>  Voluntários

                    </h2>
                    @if (Model != null && Model.Voluntarios != null)
                    {
                        if (Model.Voluntarios.Count > 0)
                        {
                            <div class="row">
                                <div class="col-xs-12 table">
                                    <table id="datatable-responsive2" class="table table-striped table-bordered dt-responsive nowrap jambo_table" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Nome</th>
                                                <th>Contato</th>
                                                <th>E-mail</th>

                                            </tr>
                                        </thead>
                                        <tbody>

                                            @for (var i = 0; i < Model.Voluntarios.Count; i++)
                                            {
                                                <tr>
                                                    <td>@Html.DisplayFor(model => model.Voluntarios[i].Id)</td>
                                                    <td>@Html.DisplayFor(model => model.Voluntarios[i].Nome)</td>
                                                    <td>@Html.DisplayFor(model => model.Voluntarios[i].Contato)</td>
                                                    <td>@Html.DisplayFor(model => model.Voluntarios[i].Email)</td>

                                                </tr>
                                            }



                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        }
                    }
                </section>
            </div>
        </div>
    </div>
</div>

Araretama.BomNaEscolaBomDeBola.Site/Views/Turma/Details.cshtml
@model Araretama.BomNaEscolaBomDeBola.Domain.Turma

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Turma</h2>
                <div class="alignright ">
                    <a href="@Url.Action("Edit", "Turma", new { id = Model.Id } )" class="btn btn-round btn-primary">
                        <i class="fa fa-edit"></i>
                        Editar
                    </a>
                    <a href="@Url.Action("Delete", "Turma", new { id = Model.Id } )" class="btn btn-round btn-danger">
                        <i class="fa fa-edit"></i>
                        Excluir
                    </a>
                </div>
             

                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <section class="content invoice">
                    <!-- title row -->
                    <div class="row">
                        <div class="col-xs-12 invoice-header">
                            <h1>
                                <i class="fa  fa-users"></i>  @Html.DisplayFor(model => model.Nome)

                            </h1>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- info row -->
                    <div class="row invoice-info">
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.DiaSemana)
                                </strong>

                                <br>@Html.DisplayFor(model => model.DiaSemana)
                            </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.HorarioInicial)
                                </strong>

                                <br>@Html.DisplayFor(model => model.HorarioInicial)
                            </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.HorarioFinal)
                                </strong>

                                <br>@Html.DisplayFor(model => model.HorarioFinal)
                            </address>
                        </div>
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.IdadeMaxima)
                                </strong>

                                <br>@Html.DisplayFor(model => model.IdadeMaxima)
                            </address>
                        </div>
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.IdadeMinima)
                                </strong>

                                <br>@Html.DisplayFor(model => model.IdadeMinima)
                            </address>
                        </div>
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>
                                    @Html.DisplayNameFor(model => model.QuantidadeDeAlunos)
                                </strong>

                                <br>@Html.DisplayFor(model => model.QuantidadeDeAlunos)
                            </address>
                        </div>



                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                    <hr />
                    <h2>
                        <i class="fa  fa-user"></i>  Alunos

                    </h2>
                    @if (Model != null && Model.Alunos != null)
                    {
                        if (Model.Alunos.Count > 0)
                        {
                            <div class="row">
                                <div class="col-xs-12 table">
                                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap jambo_table" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Nome</th>
                                                <th>Nascimento</th>
                                                <th>Escolaridade</th>
                                                <th>Contato</th>
                                                <th>Observação</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @for (var i = 0; i < Model.Alunos.Count; i++)
                                            {
                                                <tr>
                                                    <td>@Html.DisplayFor(model => model.Alunos[i].Id)</td>
                                                    <td>@Html.DisplayFor(model => model.Alunos[i].Nome)</td>
                                                    <td>@Html.DisplayFor(model => model.Alunos[i].DataNasc)</td>
                                                    <td>@Html.DisplayFor(model => model.Alunos[i].Serie)</td>
                                                    <td>@Html.DisplayFor(model => model.Alunos[i].Contato)</td>
                                                    <td>@Html.DisplayFor(model => model.Alunos[i].Observacao)</td>
                                                </tr>
                                            }



                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        }
                    }
                    <hr/>
                    <h2>
                        <i class="fa  fa-heartbeat"></i>  Voluntários

                    </h2>
                    @if (Model != null && Model.Voluntarios != null)
                    {
                        if (Model.Voluntarios.Count > 0)
                        {
                            <div class="row">
                                <div class="col-xs-12 table">
                                    <table id="datatable-responsive2" class="table table-striped table-bordered dt-responsive nowrap jambo_table" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Nome</th>
                                                <th>Contato</th>
                                                <th>E-mail</th>

                                            </tr>
                                        </thead>
                                        <tbody>

                                            @for (var i = 0; i < Model.Voluntarios.Count; i++)
                                            {
                                                <tr>
                                                    <td>@Html.DisplayFor(model => model.Voluntarios[i].Id)</td>
                                                    <td>@Html.DisplayFor(model => model.Voluntarios[i].Nome)</td>
                                                    <td>@Html.DisplayFor(model => model.Voluntarios[i].Contato)</td>
                                                    <td>@Html.DisplayFor(model => model.Voluntarios[i].Email)</td>

                                                </tr>
                                            }



                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        }
                    }
                </section>
            </div>
        </div>
    </div>
</div>

Araretama.BomNaEscolaBomDeBola.Site/Views/Turma/Index.cshtml
@model IEnumerable<Araretama.BomNaEscolaBomDeBola.Domain.Turma>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<p>
    <h2>Turmas</h2>
</p>
@if (Model != null)
{
    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap jambo_table" cellspacing="0" width="100%">
        <thead>
            <tr class="headings">
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IdadeMinima)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IdadeMaxima)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.QuantidadeDeAlunos)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HorarioInicial)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HorarioFinal)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DiaSemana)
                </th>
                <th></th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdadeMinima)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdadeMaxima)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.QuantidadeDeAlunos)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HorarioInicial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HorarioFinal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaSemana)
                </td>
                <td>


                    <a class="btn btn-primary" href="@Url.Action("Details", "Turma", new { id = item.Id })"><i class="fa fa-plus"></i></a>
                    <a class="btn btn-warning" href="@Url.Action("Edit", "Turma", new { id = item.Id })"><i class="fa fa-pencil"></i></a>
                    <a class="btn btn-danger" href="@Url.Action("Delete", "Turma", new { id = item.Id })"><i class="fa fa-trash"></i></a>

                </td>
            </tr>
        }

    </table>
}